# This file contains values from Cookiecutter

default_context:
  project_name: "language-control-diffusion"
  project_description: "Code for efficiently scaling through space, time, and tasks"
  organization: "anon"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "anon"
  email: "anon"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
